# Generated by Django 5.0.3 on 2024-03-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='чат айди телеграмм'),
        ),
    ]
