# Generated by Django 5.0.3 on 2024-03-22 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название привычки')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='место')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='время,когда необходимо выполнять привычку')),
                ('action', models.CharField(blank=True, max_length=1000, null=True, verbose_name='действие')),
                ('is_habit_good', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('periodicity', models.IntegerField(choices=[('раз в неделю', 1), ('два раза в  неделю', 2), ('три раза в неделю', 3), ('четыре раза в неделю', 4), ('пять раз в неделю', 5), ('шесть раз в неделю', 6), ('ежедневно', 7)], default=7, verbose_name='переодичность')),
                ('reward', models.CharField(blank=True, max_length=50, null=True, verbose_name='вознагрождение')),
                ('is_published', models.BooleanField(default=False, verbose_name='признак публикации')),
                ('time_to_complete', models.IntegerField(default=1, verbose_name='время на выполнение, в секундах')),
                ('habit_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
