# Generated by Django 5.0.3 on 2024-03-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.IntegerField(default=1, verbose_name='время на выполнение в секундах'),
        ),
    ]
