# Generated by Django 5.0.3 on 2024-03-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_alter_habit_time_to_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.IntegerField(choices=[(1, 'раз в неделю'), (2, 'два раза в  неделю'), (3, 'три раза в неделю'), (4, 'четыре раза в неделю'), (5, 'пять раз в неделю'), (6, 'шесть раз в неделю'), (7, 'ежедневно')], default=7, verbose_name='переодичность'),
        ),
    ]
